name: Go 1.19+ for macOS

on:
  push:
    branches:
    - 'master'
    - 'feature/**'
    - 'dev/**'

env:
  CODECOV_TOKEN: '2fc0d617-8e9a-47d7-ab58-52fa92b23741'
  MAIN_GO_VER: '1.25'
  MAIN_HOST_OS: 'macos-latest'

jobs:
  go_test_and_coverage:
    strategy:
      max-parallel: 6
      matrix:
        GO_VER: ['1.19', '1.20', '1.21', '1.22', '1.23', '1.24', '1.25', '1.26']
        HOST_OS: ['macos-latest']

    runs-on: ${{ matrix.HOST_OS }}

    steps:

    - name: Checkout Repositary
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.GO_VER }}
      id: go

    - name: Get Dependencies
      run: |
        echo GO_VER = ${{ matrix.GO_VER }}
        go get golang.org/x/tools/cmd/cover
        go install github.com/mattn/goveralls || go get github.com/mattn/goveralls
        go get .

    - name: Go test
      run: |
        go test -v -failfast -cover -covermode=atomic -coverprofile=coverage.out
